### ISSUE TITLE
Install Mulping (Windows/Pycharm)

### ISSUE THREAD

**Issue by Codein99** [deivshon/mulping#2]
Hey, 

thank you for your work. Look very intresting and I will try it, but when I will install it with "pip install mulping" its say: 

_ERROR: Could not find a version that satisfies the requirement mulping (from versions: none)
ERROR: No matching distribution found for mulping_

In Pycharm I can't find it. I have also tryed it manual but it also doesnt look really good... Someone have a hint for me or eventually I doesnt understand something wrong?

**Comment by deivshon** [comment]
That is correct, mulping is not published as a Python package, you have to use pip only to install the requests module if you are on Windows and don't have it installed yet, by running
```
$ pip install requests
```
Then you can download mulping from this repository and run it normally with python
```
$ python3 ./mulping.py
```

If you want to have it as a global command I believe you can achieve it by placing it in one of the PATH tracked folders

Let me know if everything works fine :)

**Comment by Codein99** [comment]
Oh, now I understand. Thank you <3

But I have to use this answer:
[https://stackoverflow.com/questions/57131654/using-utf-8-encoding-chcp-65001-in-command-prompt-windows-powershell-window](url)

because I become this error "utf-8' codec can t decode byte 0x81".

Don't know if this has something to do with your Project ;)
